language: php

services:
  - mysql

php:
  - 7.2
  - 7.3

before_script:
  - cp .env.travis .env
  - mysql -e 'create database cosst;'
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan key:generate
  - php artisan migrate
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - bash <(curl -s https://codecov.io/bash)
